[package]
name = "beancount-lsp"
version = "0.0.0"
authors = ["Trim21 <trim21.me@gmail.com>"]
edition = "2024"
license = "MIT"
description = "Minimal Beancount LSP using beancount-parser"

[dependencies]
anyhow = "1"
beancount-parser = { workspace = true }
beancount-tree-sitter = { workspace = true }
clap = { version = "4", features = ["derive"] }
glob = "0.3"
ropey = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { workspace = true }
tower-lsp = { workspace = true }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt"] }

[dev-dependencies]
tempfile = "3"
