[package]
name = "beancount-lsp-py"
version = { workspace = true }
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
beancount-lsp = { path = "../lsp", features = ["pyo3"] }
pyo3 = { version = "0.28.0", features = ["abi3-py310", "generate-import-lib"] }
tokio = { workspace = true }
