name: Build Python Wheels

on:
  workflow_call:

jobs:
  sdist:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v7
        with:
          github-token: '${{ github.token }}'

      - run: uv build --sdist .

      - name: Upload sdist
        uses: actions/upload-artifact@v6
        with:
          name: wheels-sdist
          path: ./dist/*.tar.gz
          if-no-files-found: 'error'

  wheel:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - runner: macos-15
            target: aarch64
          - runner: macos-15-intel
            target: x64

          - runner: windows-latest
            target: x64
          - runner: windows-11-arm
            target: aarch64

          - runner: ubuntu-24.04
            target: x64
          - runner: ubuntu-24.04-arm
            target: aarch64

    steps:
      - uses: actions/checkout@v6

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - uses: actions/setup-python@v6
        if: ${{ runner.os != 'Linux' }}
        with:
          python-version: '3.14'

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.platform.target }}
          args: ${{ runner.os == 'Linux' && '--release --out dist --zig' || '--release --out dist' }}
          container: 'off'
          # https://github.com/tree-sitter/tree-sitter/issues/4186
          manylinux: '2_17'

      - run: ls -ahl ./dist/
        shell: bash

      - name: Upload wheels
        uses: actions/upload-artifact@v6
        with:
          name: wheels-${{ runner.os }}-${{ matrix.platform.target }}
          path: ./dist/*.whl
          if-no-files-found: 'error'

  merge-wheel-artifact:
    runs-on: ubuntu-24.04
    needs: ['sdist', 'wheel']
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v6
        with:
          name: wheel
          pattern: wheels-*
